#!/bin/bash
lua -lluacov spec.lua
luacov

printf "\e[4m"
tail -1000 luacov.report.out | grep 'File'

# List out coverage < 100%
printf "\e[0m\e[92m"
tail -1000 luacov.report.out | egrep '/*.lua [0-9]{0}' | awk '0+$4 >= 100'

printf "\e[91m"
tail -1000 luacov.report.out | egrep '/*.lua [0-9]{0}' | awk '0+$4 < 100'
